services:
  - type: web
    name: n8n-maria-eduarda
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_USER_MANAGEMENT_JWT_SECRET
        generateValue: true

